site_name: WITNESS4Climate
site_url: https://www.witness4climate.org/html/tests
theme: 
  name: readthedocs
  custom_dir: overrides
nav:
  - SoSTrades :  
    - Installation : 
       - Basic : SoSTrades/install_basic.md
       - Platform : SoSTrades/install_platform.md
  - About : About.md 
  
